[package]
name = "estebanborai-github-io"
version = "0.1.0"
authors = ["Esteban Borai <estebanborai@gmail.com>"]
edition = "2018"

[dependencies]
console_error_panic_hook = "0.1.6"
wasm-bindgen = "0.2.73"
wee_alloc = "0.4.5"
yew = "0.17.3"
