version: '3'

services:
  database:
    image: postgres:13
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/docker/volumes/database:/var/lib/postgresql/data
    restart: always
