use std::str::FromStr;

use yew::prelude::*;
use yew_router::prelude::*;

/// Do note that the implementation generated by the derive macro for Switch will
/// try to match each variant in order from first to last, so if any route could
/// possibly match two of your specified to annotations, then the first one will
/// match, and the second will never be tried. For example, if you defined the
/// following Switch, the only route that would be matched would be AppRoute::Home.
#[derive(Switch, Debug, Clone)]
pub enum AppRoute {
    #[to = "/articles/{id}"]
    Article(String),
    #[to = "/articles"]
    Articles,
    #[to = "/"]
    Home,
}
