name: Deploy Production
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          ref: 'main'

      - name: Install NodeJS
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Builds for Production
        env:
          NODE_ENV: 'production'
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: 'estebanborai-dotcom'
          directory: ./.svelte-kit/cloudflare
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
