name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Setup "wasm32-unknown-unknown" target
        run: rustup target add wasm32-unknown-unknown

      - name: Setup "wasm-bindgen-cli"
        run: cargo install wasm-bindgen-cli

      # https://github.com/thedodd/trunk#install
      - name: Install Trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.11.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      - name: Build
        run: ./trunk build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
