name: Deploy
on: 'release'

env:
  CF_EMAIL: ${{ secrets.CF_EMAIL }}
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
  CF_ENVIRONMENT: 'production'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: yarn install

      - name: Create wrangler.toml
        run: ./bin/make-wrangler

      - name: Publish
        run: ./bin/publish
