name: Deploy Client Production
on:
  push:
    branches:
      - main

env:
  CF_EMAIL: ${{ secrets.CF_EMAIL }}
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
  CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
  CF_ENVIRONMENT: 'production'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Setup "wasm32-unknown-unknown" target
        run: rustup target add wasm32-unknown-unknown

      - name: Setup "wasm-bindgen-cli"
        run: cargo install wasm-bindgen-cli

      - name: Install Trunk
        run: cargo install --locked trunk

      - name: Build
        run: trunk build --release ./client/index.html

      - name: Setup "wrangler"
        run: cargo install wrangler

      - name: Create wrangler.toml
        run: ./bin/make-wrangler

      - name: Publish
        run: wrangler publish --env $CF_ENVIRONMENT
