name: Build & Release

on:
  push:
    branches:
      - ci

jobs:
  release:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Publish with gh-pages
        run: npm run deploy
